[workspace]
authors = ["mharv <mitch.k.harvey@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "day6"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025121020,<0.27"
