[workspace]
authors = ["mharv <mitchell.harvey@arup.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "day1"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025113005,<0.27"
